language: go

go:
  - 1.8.x
  - 1.9.x

go_import_path: github.com/sourcegraph/go-langserver

install:
  - go get -d -t ./...
  - go test -i ./...

script:
  - cd $TRAVIS_BUILD_DIR
  - go test -race -v ./...
