version: "{build}"
shallow_clone: true
clone_folder: c:\gopath\src\github.com\sourcegraph\go-langserver
environment:
  GOPATH: c:\gopath
install:
  - set PATH=C:\msys64\mingw64\bin;%PATH%;%GOPATH%\bin
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d -t ./...
  - go test -i ./...
build_script:
  - go test -race -v ./...
